PersonalBlog.Web/Areas/Admin/Controllers/ArticleController.cs
using AutoMapper;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using YoutubeBlog.Entity.Entities.Concrete;
using YoutubeBlog.Entity.Models.DTOs.Articles;
using YoutubeBlog.Service.Services.Abstract;
using YoutubeBlog.Web.Const;
using YoutubeBlog.Web.ResultMessages;

namespace YoutubeBlog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        private readonly IValidator<Article> _articleValidator;
        private readonly IToastNotification _toast;
        public ArticleController(IArticleService articleService, ICategoryService categoryService, IMapper mapper, IValidator<Article> articleValidator,
            IToastNotification toast)
        {
            _articleService = articleService;
            _categoryService = categoryService;
            _mapper = mapper;
            _articleValidator = articleValidator;
            _toast = toast;
        }

        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin},{RoleConst.User}")]
        public async Task<IActionResult> Index()
        {
            var articles = await _articleService.GetAllArticlesWithCategoryNonDeletedAsync();
            return View(articles);
        }

        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> DeletedArticle()
        {
            var articles = await _articleService.GetAllDeletedArticlesWithCategoryAsync();
            return View(articles);
        }


        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> Add()
        {
            var categories = await _categoryService.GetAllCategoriesNonDeleteAsync();
            return View(new ArticleAddDto
            {
                Categories = categories
            });
        }

        [HttpPost]
        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> Add(ArticleAddDto articleAddDto)
        {
            var map = _mapper.Map<Article>(articleAddDto);
            var result = await _articleValidator.ValidateAsync(map);

            if (result.IsValid)
            {
                var title = await _articleService.CreateArticleAsync(articleAddDto);

                if(title != null)
                {
                    _toast.AddSuccessToastMessage(Messages.Article.Add(title), new ToastrOptions { Title = Messages.ToastTitle.Success });
                }
                else
                {
                    _toast.AddErrorToastMessage(Messages.GlobalMessage.Error, new ToastrOptions { Title = Messages.ToastTitle.Error });
                }

                return RedirectToAction("Index", "Article", new { Area = "Admin" });
            }
            else
            {
                result.AddToModelState(this.ModelState);
                articleAddDto.Categories = await _categoryService.GetAllCategoriesNonDeleteAsync();

                return View(articleAddDto);
            }
        }

        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> Update(Guid articleId)
        {
            var article = await _articleService.GetArticleWithCategoryNonDeletedAsync(articleId);

            if (article != null)
            {
                var articleUpdateDto = _mapper.Map<ArticleUpdateDto>(article);
                articleUpdateDto.Categories = await _categoryService.GetAllCategoriesNonDeleteAsync();

                return View(articleUpdateDto);
            }

            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> Update(ArticleUpdateDto articleUpdateDto)
        {
            var map = _mapper.Map<Article>(articleUpdateDto);
            var result = await _articleValidator.ValidateAsync(map);

            if (result.IsValid)
            {
                var title = await _articleService.UpdateArticleAsync(articleUpdateDto);

                if (title != null)
                {
                    _toast.AddSuccessToastMessage(Messages.Article.Update(title), new ToastrOptions { Title = Messages.ToastTitle.Success });
                }
                else
                {
                    _toast.AddErrorToastMessage(Messages.GlobalMessage.Error, new ToastrOptions { Title = Messages.ToastTitle.Error });
                }

                return RedirectToAction("Index", "Article", new { Area = "Admin" });
            }
            else
            {
                result.AddToModelState(this.ModelState);
                articleUpdateDto.Categories = await _categoryService.GetAllCategoriesNonDeleteAsync();

                return View(articleUpdateDto);
            }
        }

        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> Delete(Guid articleId)
        {
            var title = await _articleService.SafeDeleteArticleAsync(articleId);

            if (title != null)
            {
                _toast.AddSuccessToastMessage(Messages.Article.Delete(title), new ToastrOptions { Title = Messages.ToastTitle.Success });
            }
            else
            {
                _toast.AddErrorToastMessage(Messages.GlobalMessage.Error, new ToastrOptions { Title = Messages.ToastTitle.Error });
            }

            return RedirectToAction("Index", "Article", new { Area = "Admin" });
        }

        [Authorize(Roles = $"{RoleConst.SuperAdmin},{RoleConst.Admin}")]
        public async Task<IActionResult> UndoDelete(Guid articleId)
        {
            var title = await _articleService.UndoDeleteAsync(articleId);

            if (title != null)
            {
                _toast.AddSuccessToastMessage(Messages.Article.UndoDelete(title), new ToastrOptions { Title = Messages.ToastTitle.Success });
            }
            else
            {
                _toast.AddErrorToastMessage(Messages.GlobalMessage.Error, new ToastrOptions { Title = Messages.ToastTitle.Error });
            }

            return RedirectToAction("DeletedArticle", "Article", new { Area = "Admin" });
        }
    }
}

PersonalBlog.Web/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using YoutubeBlog.Service.Services.Abstract;

namespace YoutubeBlog.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }
        public async Task<IActionResult> Index(Guid articleId)
        {
            var article = await _articleService.GetArticleWithCategoryNonDeletedAsync(articleId);
            return View(article);
        }
    }
}

PersonalBlog.Web/ViewComponents/Article/GetArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using YoutubeBlog.Service.Services.Abstract;

namespace YoutubeBlog.Web.ViewComponents.Article
{
    public class GetArticlesViewComponent : ViewComponent
    {
        private readonly IArticleService _articleService;

        public GetArticlesViewComponent(IArticleService articleService)
        {
            _articleService = articleService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var articles = await _articleService.GetLastNPostsAsync(5);
            return View(articles);
        }
    }
}

PersonalBlog.Web/ViewComponents/Category/GetCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using YoutubeBlog.Service.Services.Abstract;

namespace YoutubeBlog.Web.ViewComponents.Category
{
    public class GetCategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public GetCategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryService.GetFirstNCategoriesAsync(7);
            return View(categories);
        }
    }
}

PersonalBlog.Web/Views/Article/Index.cshtml
@model ArticleDto

@{
    ViewData["Title"] = "Ana Sayfa";
}

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="~/images/blog-post-02.jpg" alt="">
                                </div>
                                <div class="down-content">
                                    <span>@Model.Category.Name</span>
                                    <a href="post-details.html"><h4>@Model.Title</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">@Model.CreatedBy</a></li>
                                        <li><a href="#">@Model.CreatedDate</a></li>
                                        @*<li><a href="#">10 Comments</a></li>*@
                                    </ul>
                                    <p style="min-height: 80px;">
                                        @Model.Content
                                    </p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    <li><a href="#">@Model.Category.Name</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item comments">
                                <div class="sidebar-heading">
                                    <h2>4 yorum</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        <li>
                                            <div class="author-thumb">
                                                <img src="~/images/comment-author-01.jpg" alt="">
                                            </div>
                                            <div class="right-content">
                                                <h4>Charles Kate<span>May 16, 2020</span></h4>
                                                <p>Fusce ornare mollis eros. Duis et diam vitae justo fringilla condimentum eu quis leo. Vestibulum id turpis porttitor sapien facilisis scelerisque. Curabitur a nisl eu lacus convallis eleifend posuere id tellus.</p>
                                            </div>
                                        </li>
                                        <li class="replied">
                                            <div class="author-thumb">
                                                <img src="~/images/comment-author-02.jpg" alt="">
                                            </div>
                                            <div class="right-content">
                                                <h4>Thirteen Man<span>May 20, 2020</span></h4>
                                                <p>In porta urna sed venenatis sollicitudin. Praesent urna sem, pulvinar vel mattis eget.</p>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="author-thumb">
                                                <img src="~/images/comment-author-03.jpg" alt="">
                                            </div>
                                            <div class="right-content">
                                                <h4>Belisimo Mama<span>May 16, 2020</span></h4>
                                                <p>Nullam nec pharetra nibh. Cras tortor nulla, faucibus id tincidunt in, ultrices eget ligula. Sed vitae suscipit ligula. Vestibulum id turpis volutpat, lobortis turpis ac, molestie nibh.</p>
                                            </div>
                                        </li>
                                        <li class="replied">
                                            <div class="author-thumb">
                                                <img src="~/images/comment-author-02.jpg" alt="">
                                            </div>
                                            <div class="right-content">
                                                <h4>Thirteen Man<span>May 22, 2020</span></h4>
                                                <p>Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo.</p>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item submit-comment">
                                <div class="sidebar-heading">
                                    <h2>Yorumun</h2>
                                </div>
                                <div class="content">
                                    <form id="comment" action="#" method="post">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-12">
                                                <fieldset>
                                                    <input name="name" type="text" id="name" placeholder="Isminiz" required="">
                                                </fieldset>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <fieldset>
                                                    <input name="email" type="text" id="email" placeholder="Emailiniz" required="">
                                                </fieldset>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <fieldset>
                                                    <input name="subject" type="text" id="subject" placeholder="Başlık">
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <textarea name="message" rows="6" id="message" placeholder="Yorum..." required=""></textarea>
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <button type="submit" id="form-submit" class="main-button">Yorum Yap</button>
                                                </fieldset>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form id="search_form" asp-controller="Home" asp-action="Search" method="GET">
                                    <input type="text" name="keyword" class="searchText" placeholder="Arama yapınız..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Son Makaleler</h2>
                                </div>
                                <div class="content">

                                    @await Component.InvokeAsync("GetArticles")

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading">
                                    <h2>Kategoriler</h2>
                                </div>
                                <div class="content">
                                    
                                    @await Component.InvokeAsync("GetCategories")

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>